import Link from "next/link";
import { DeviceVisual } from "@/components/DeviceVisual";
import { InquiryForm } from "@/components/InquiryForm";
import { SiteShell } from "@/components/SiteShell";

export default function HomePage() {
  return <SiteShell><div id="main">
    <section className="hero" aria-labelledby="hero-title"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="container hero-grid">
      <div className="hero-copy reveal visible"><div className="eyebrow"><span/>Designed for frontline care</div><h1 id="hero-title">Clinical clarity.<br/><em>Where it matters most.</em></h1><p className="hero-lead">Tyqora builds AI-assisted diagnostic tools for healthcare teams working in the world&apos;s most demanding environments.</p><div className="hero-actions"><Link className="button button-primary button-large" href="/product">Discover the stethoscope <span>→</span></Link><a className="text-link" href="#how-it-works">See how it works <span>↓</span></a></div><div className="hero-proof"><div className="proof-avatars" aria-hidden="true"><span>DR</span><span>RN</span><span>CHW</span></div><p><strong>Built alongside clinicians</strong><br/>for low-resource and offline settings</p></div></div>
      <DeviceVisual/>
    </div><div className="container hero-foot"><span>AI-assisted auscultation</span><span>Offline-first</span><span>Made for diverse clinical settings</span></div></section>

    <section className="section challenge" id="solution"><div className="container split-heading reveal visible"><div><div className="section-kicker">The challenge</div><h2>Good care should not depend on a postcode.</h2></div><div><p>Frontline teams often make critical decisions with limited tools, unreliable connectivity, and overwhelming patient volumes. We design for that reality.</p><a className="text-link dark" href="#how-it-works">Our approach <span>→</span></a></div></div><div className="container challenge-grid">
      {[['01','Late detection','Subtle respiratory signals can be difficult to identify in noisy, time-pressured environments.'],['02','Uneven access','Specialist expertise is scarce outside urban centres, leaving frontline workers without timely support.'],['03','Fragmented data','Clinical observations are frequently lost between paper records and disconnected systems.']].map(([n,title,text],i)=><article className={`challenge-card${i===1?' featured':''}`} key={n}><span>{n}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 15h3l2-7 4 12 3-9 2 4h2" fill="none" stroke="currentColor"/></svg><h3>{title}</h3><p>{text}</p></article>)}
    </div></section>

    <section className="section product-story" id="how-it-works"><div className="container product-story-grid"><div className="product-panel reveal visible"><div className="panel-grid"/><div className="scan-ring ring-one"/><div className="scan-ring ring-two"/><div className="chestpiece"><div className="chestpiece-inner"><svg viewBox="0 0 24 24"><path d="M5 12h3l2-5 4 10 2-5h3"/></svg></div></div><div className="live-card"><span className="live-dot"/><small>LIVE ANALYSIS</small><strong>Vesicular pattern</strong><em>Confidence 94%</em></div></div><div className="story-copy"><div className="section-kicker light">Introducing TYQ-DST01</div><h2>A familiar instrument.<br/><em>More intelligent.</em></h2><p>Our digital stethoscope captures, clarifies, and analyses heart and lung sounds—giving clinicians consistent decision support at the point of care.</p><ol className="steps"><li><span>01</span><div><strong>Capture clearly</strong><p>Digital sensing and active noise reduction preserve clinically relevant sound.</p></div></li><li><span>02</span><div><strong>Analyse locally</strong><p>On-device models support assessment even when connectivity is unavailable.</p></div></li><li><span>03</span><div><strong>Act with context</strong><p>Simple, interpretable guidance supports the appropriate next step.</p></div></li></ol><Link className="button button-light" href="/product">View product details →</Link></div></div></section>

    <section className="section impact" id="impact"><div className="container impact-heading"><div><div className="section-kicker">Designed for impact</div><h2>Built around the realities of care.</h2></div><p>Every design decision starts with the people delivering and receiving healthcare across diverse African communities.</p></div><div className="container impact-grid"><article className="impact-card wide"><div><span className="pill">Offline-first</span><h3>Intelligence without dependence on the internet.</h3><p>Core assessment works locally, with secure synchronisation when a connection becomes available.</p></div><div className="connection-visual"><i/><i/><i/><b>DEVICE READY</b></div></article><article className="impact-card"><span className="icon-box">✦</span><h3>Designed with clinicians</h3><p>Workflows shaped by the pace, pressure, and constraints of frontline teams.</p></article><article className="impact-card dark-card"><span className="icon-box">⌁</span><h3>Made to endure</h3><p>Durable hardware, efficient power use, and straightforward maintenance.</p></article><article className="impact-card quote-card wide"><blockquote>“Technology earns trust when it makes the clinician more capable—and the patient more visible.”</blockquote><p>Our product principle</p></article></div></section>

    <section className="section about" id="about"><div className="container about-grid"><div><div className="section-kicker light">About Tyqora</div><h2>Engineering intelligence.<br/><em>Advancing human care.</em></h2></div><div><p>Tyqora is a healthcare technology company building accessible clinical intelligence for African health systems. We combine biomedical engineering, responsible AI, and human-centred design.</p><p>Our ambition is simple: help every healthcare worker make better-informed decisions, wherever they practise.</p></div></div><div className="container values-grid"><article><span>01</span><h3>Who we are</h3><p>Engineers and health practitioners working together to solve meaningful care gaps with resilient medical technology.</p></article><article><span>02</span><h3>Our mission</h3><p>Design and deploy intelligent biomedical tools that improve access to timely, well-informed care in underserved settings.</p></article><article><span>03</span><h3>Our vision</h3><p>An African biomedical ecosystem where advanced healthcare technology is locally relevant, accessible, and built to endure.</p></article></div><div className="container alignment-row"><strong>Aligned for impact</strong><span><i>03</i> Good health and well-being</span><span><i>09</i> Industry and innovation</span><span><i>AF</i> Built for African health systems</span></div></section>
    <section className="section contact-section" id="contact"><div className="container contact-card"><div><div className="section-kicker">Partnerships</div><h2>Let&apos;s build healthier systems together.</h2><p>We welcome conversations with clinicians, hospitals, researchers, distributors, and public-health partners.</p></div><InquiryForm/></div></section>
  </div></SiteShell>;
}
