"use client";
import Link from "next/link";
import { useState } from "react";

export function ProductClient() {
  const [quantity,setQuantity]=useState(1);
  function save(){ sessionStorage.setItem("tyqora_quantity",String(quantity)); }
  return <div className="inner-page"><section className="product-hero container"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><span>TYQ-DST01</span></div><div className="product-grid">
    <div className="product-gallery reveal visible"><div className="gallery-badge">Early access</div><div className="product-device-mini"><div className="mini-screen"><small>ANALYSING</small><svg viewBox="0 0 160 50"><polyline points="0,28 25,28 33,8 43,45 55,20 65,28 91,28 100,12 111,40 121,22 130,28 160,28"/></svg></div><strong>TYQORA</strong><span>TYQ-DST01</span><i/></div><div className="gallery-caption"><span>01</span><p>Precision-milled housing<br/>Clinical-grade digital sensing</p></div></div>
    <div className="product-info"><div className="section-kicker">Digital auscultation</div><h1>TYQ-DST01</h1><p className="product-subtitle">AI-assisted digital stethoscope</p><p className="product-description">Built to make heart and lung sound assessment clearer, more consistent, and easier to document across a wide range of clinical environments.</p><div className="feature-list"><div><svg viewBox="0 0 24 24"><path d="M4 12h3l2-6 5 12 2-6h4"/></svg><span><strong>Enhanced sound capture</strong><small>Active filtering and configurable amplification</small></span></div><div><svg viewBox="0 0 24 24"><path d="M12 3v18M5 8c0-3 2-4 4-4s3 2 3 4M19 8c0-3-2-4-4-4s-3 2-3 4"/></svg><span><strong>AI-assisted classification</strong><small>Interpretable support for respiratory patterns</small></span></div><div><svg viewBox="0 0 24 24"><path d="M6 18 18 6M8 6h10v10"/></svg><span><strong>Offline by design</strong><small>Core workflows remain available without internet</small></span></div></div><div className="price-row"><div><small>Indicative unit price</small><strong>$100</strong></div><div className="quantity"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} aria-label="Decrease quantity">−</button><output>{quantity}</output><button onClick={()=>setQuantity(Math.min(20,quantity+1))} aria-label="Increase quantity">+</button></div></div><Link className="button button-primary button-large full-button" href="/checkout" onClick={save}>Request an order →</Link><p className="medical-note">TYQ-DST01 is an investigational decision-support product. Availability and regulatory status vary by market. It does not replace clinical judgement.</p></div>
  </div></section><section className="spec-section"><div className="container"><div className="section-kicker light">At a glance</div><div className="spec-grid"><div><strong>10+ hrs</strong><span>Typical battery life</span></div><div><strong>USB-C</strong><span>Charging and data</span></div><div><strong>Offline</strong><span>Core AI workflow</span></div><div><strong>Encrypted</strong><span>Local records</span></div></div></div></section></div>;
}
